### ISSUE TITLE
Organize configuration file

### ISSUE THREAD

**Issue by guillermo-carrasco** [SciLifeLab/TACA#107]
@robinandeer didn't we start a conversation about this some time ago? I can't find it... in any case, the onfiguration file for TACA starts to be a bit unorganized. What about this simple structure:

* Top level section for common configs for all subcommands, like db_credentials or contact
* A dedicated section for each subcommand

Example

```yaml
#Common configs
contact: guillermo.carrasco@scilifelab.se
log:
    log_file: /Users/guillem/log/taca.log

#Storage subcommand configs
storage:
    data_dirs:
        - /Users/guillem/tmp/
    # These are the directories where the data waits to be archived (nosync for production NGI)
    archive_dirs:
        - /Users/guillem/tmp/nosync
    irods:
        irodsHome: ...

#Analysis subcommand configs
analysis:
    hiseq_data: /Users/guillem/test
    miseq_data: /Users/guillem/srv/illumina/miseq_data
    mfs: /srv/mfs
    status_dir: /Users/guillem/log
    bcl2fastq:
        XTen: /home/hiseq.bioinfo/opt/bcl2fastq/bin/bcl2fastq
        use-bases-mask: Y8,I8,Y8
    samplesheets_dir: /srv/mfs/samplesheets
    analysis_serrver:
        user: ...
        host: ...
        port: ..
        data_archive: ...
        include:
            - "*.xml"
            - "*.htm"
            - "*.fastq.gz"
```

**Comment by robinandeer** [comment]
Probably, but I think that was in Slack or something.

I think this is a good and logical idea! I would add that is great to sync up command line options with the config file. This way Click provides the opportunity to set up defaults for the commands automatically :smile:

The top level would then be options available for the root command (group)

**Comment by guillermo-carrasco** [comment]
that sounds good :) Is [this](http://click.pocoo.org/4/commands/#overriding-defaults) what you're referring to?

**Comment by robinandeer** [comment]
Great, ``default_map`` is exactly what I mean!

Implementation example:
https://github.com/robinandeer/chanjo/blob/master/chanjo/cli.py#L52

How the chanjo config looks like:
```toml
# chanjo config

dialect = "sqlite"
db = "/home/vagrant/demo/coverage.sqlite"

[annotate]
cutoff = 10

[report]
panel = "/home/vagrant/demo/dbCMMS.v1.1.hgnc.txt"
panel_caption = "dbCMMS v1.1"
port = 5000
host = "0.0.0.0"
```
